seed: 2
run_dir: transformer_00000000_abcd
training_ids: /project/data/train_participants_ABCD.tsv
validation_ids: /project/data/valid_participants_ABCD.tsv
input_height: 24
input_width: 28
input_depth: 24
order_type: raster_scan
transposed_1: 0
transposed_2: 0
transposed_3: 0
transposed_4: 0
transposed_5: 0
reflected_rows: 0
reflected_cols: 0
reflected_depths: 0
n_embd: 64
n_layers: 16
n_heads: 8
local_attn_heads: 4
local_window_size: 256
ff_mult: 4
ff_glu: 0
rotary_position_emb: 0
axial_position_emb: 0
emb_dropout: 0.3
ff_dropout: 0.3
attn_dropout: 0.3
latent_resolution: low
redrawn_freq: 3
vqvae_uri: /project/mlruns/0/f89cb9ee1a824324b04df9f4b7a8e430/artifacts/final_model
batch_size: 2
lr: 0.001
lr_decay: 0.999997
n_epochs: 200
eval_freq: 3
augmentation: 0
vbm_img: 1
num_workers: 16
experiment: TRANSFORMER_low_ABCD_00000000