seed: 2
run_dir: vqvae_low_abcd
training_ids: /project/data/train_participants_ABCD.tsv
validation_ids: /project/data/valid_participants_ABCD.tsv
n_embed: 64
embed_dim: 64
n_alpha_channels: 2
n_channels: 256
n_res_channels: 256
n_res_layers: 3
p_dropout: 0.1
latent_resolution: low
vq_decay: 0.5
commitment_cost: 0.25
batch_size: 12
lr: 0.0005
lr_decay: 0.9999
n_epochs: 200
eval_freq: 6
augmentation: 0
vbm_img: 1
num_workers: 16
experiment: VQVAE_low_ABCD