#General
seed: 2 #random seed to set determinism
run_dir: vqvae_low_abcd #model location to resume
training_ids: /project/data/train_participants_ABCD.tsv #training ids file location
validation_ids: /project/data/valid_participants_ABCD.tsv #validation ids file location

#Model
n_embed: 64 # size of discrete latent space (K-way categorical)
embed_dim: 64 # dimensionality of each latent embedding vector
n_alpha_channels: 2 # number of alpha channels in input image
n_channels: 256 # number of channels in the encoder and decoder
n_res_channels: 256 # number of channels in the residual layers
n_res_layers: 3 #number of residual blocks
p_dropout: 0.1 #dropout
latent_resolution: low #latent space resolution (low or high)
vq_decay: 0.5 #vq_decay
commitment_cost: 0.25 #commitment cost

#Training
batch_size: 12 #batch size
lr: 0.0005 #learning rate
lr_decay: 0.9999 #learning rate decay
n_epochs: 200 #number of epochs
eval_freq: 6 #evaluation occurs between eval_freq number of epochs
augmentation: 0 #use augmentation: 1=True or 0=False
vbm_img: 1 #use vbm: 1=True or 0=False
num_workers: 16 #number of loader workers
experiment: VQVAE_low_ABCD #mlflow experiment name